### ISSUE TITLE
Enormous size of video snapshot

### ISSUE THREAD

**Issue by ogliznutsa** [tomaszzmuda/Xabe.FFmpeg#231]
Hi,

I use the following code to get video snapshot:

`await Xabe.FFmpeg.Conversion.Snapshot(videoPath, thumbnailPath, TimeSpan.Zero).Start();`

As a result I get 1.7mb .png snapshot of 1mb .mp4 video ([video link](https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4)) 

FFmpeg is called with the following params: `-ss 00:00:00 -i "{input}" -n -threads 4 -c:v png -frames:v 1 -map 0:0 "{output}"`.

Looks like `.mp4 (h264)` -> `.png` coversion makes snapshot so big. The output gets small size if I run ffmpeg manually without `-c:v png` and with .jpg output.

Hovewer I can't omit `-c:v png` with Xabe.FFmpeg.

**Comment by tomaszzmuda** [comment]
Hello

Thanks for info. I will do something with that.
Unfortunately, I cannot break backward compatibility and just change png to something different. 

It probably take some time due to other tasks.
Look how implementation on Snapshot method looks like:
![image](https://user-images.githubusercontent.com/13612984/75572490-29ead100-5a5b-11ea-96c1-19a2291f4b11.png)

If you remove SetCodec method and add .jpg extension to output file it should be correct.

**Comment by ogliznutsa** [comment]
The workaround works nicely, thanks!

**Comment by tomaszzmuda** [comment]
#234 
Merged :)
Now output format can be defined just by name.
It will be available in next minor version.

**Comment by ogliznutsa** [comment]
Hi,
Everything works like a charm - it doesn't force png when creating snapshots, but looks like the [documentation (chapter "Snapshot")](https://ffmpeg.xabe.net/docs.html) is outdated, it says that:

> Conversion always returns snapshot in png file format so outputPath should be with correct extension.

**Comment by tomaszzmuda** [comment]
Thanks @ogliznutsa 
I changed that text
