### ISSUE TITLE
FFmpeg fails with convserions if the user name has a space in the name

### ISSUE THREAD

**Issue by lreben** [tomaszzmuda/Xabe.FFmpeg#345]
In some situation, ffmpeg fails with a conversion if there is a space in the user name. For example, it says a file or directory is not found if the user name is path is C:\Users\A B\. It outputs "C:\Users\A" file or directory not found.

This is happening on Windows 10, running inside Visual Studio 2019, and FFmpeg is installed via NuGet (4.4.0). FFmpeg is copied to output direction It is not all conversions, but occurs when trying to make a video from image frames. The code in question is this:
 string name = "\"clip\\" + clipSaveName+ ".mp4\"";
IConversion convert = FFmpeg.Conversions.New()
                    .SetOverwriteOutput(true)
                    .SetInputFrameRate(30)
                    .BuildVideoFromImages(files)
                    .SetFrameRate(30)
                    .SetPixelFormat(Xabe.FFmpeg.PixelFormat.yuv420p)
                    .SetOutput(name);

Moving the Visual studio project to a another drive without a space still causes the same problem. For example, I could run the project in "D:\Users\C\MyProject", and I get the same "C:\Users\A" file or directory not found error.

**Comment by tomaszzmuda** [comment]
Hello @lreben 
It took my some time but I found cause. Some paths wasn't escaped properly. 
Here is PR with fix: #350

**Comment by lreben** [comment]
Thank you!

**Comment by muebel201** [comment]
Hi - I'm still observing this exact problem, wherein a conversion fails if the username contains a space.  Can you confirm that the fix is in V5.0.2?

Here's the exception I'm getting:
Xabe.FFmpeg.Exceptions.ConversionException: ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.1.1 (GCC) 20190807
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
C:\Users\LAB: No such file or directory
   at Xabe.FFmpeg.FFmpegWrapper.<>c__DisplayClass11_0.<RunProcess>b__0()

**Comment by lreben** [comment]
Unfortunately no. This was a student that had the problem, and they
graduated awhile back. I'd rather not make a new account just to check this
on my side. I cannot confirm.
